apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: gemma-2-2b
  namespace: nim-service
spec:
  image:
    repository: nvcr.io/nim/google/gemma-2-2b-instruct
    tag: "1.4"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  env:
   - name: NIM_MAX_MODEL_LEN
     value: "4096"
  storage:
    emptyDir:
      sizeLimit: 30Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: In
            values:
            - auto
  tolerations:
    - key: gpu-nodeclass
      operator: Equal
      value: "true"
      effect: NoSchedule
  resources:
    limits:
      nvidia.com/gpu: "1"
      memory: "24Gi"
    requests:
      nvidia.com/gpu: "1"
      memory: "24Gi"
  expose:
    service:
      type: ClusterIP
      port: 8000
